const STOPWORDS = ['at', 'as', 'am', 'a', 'an', 'am', 'above', 'around', 'about', 
'actually', 'always', 'among', 'be', 'been', 'both', 'can', 'consider', 'could', "couldn't", 'day', 'do', 'dont',
'done', 'did', 'each', 'enough', 'even', 'every', 'for', 'from', 'go', 'get', 'have', "shouldn't", 'feel', 'other', 'others', 'really', 'place', 'placed', 'thats', 'until',
'had', 'how', 'he', 'i', 'him', 'her', "I'm", 'let', 'most', 'much', 'might', 'may', 
'must', 'maybe', 'no', 'not', 'never', 'over', 'of', 'one', 'off', 'on', 'only', 
'put', 'rest', 'so', 'she', 'such', 'to', 'that', 'than', 'then', 'two', 'too', 
'three', 'ten', 'toward', 'today', 'very', 'us', 'we', 'with', 'without', 'who', 
'which', 'why', 'you', 'yet', "whose", "must", "returned", "named", "might", 
"become", "became", "youre", "return", "told", "give", "given", "almost", "around", 
"about", "against", "among", "returning", "coming", "thus", "went", "like", 
"liked", "using", "use", "used", "named", "names", "name", "sent", "taken", "took", "us", "while", "without", "under", "upon", "see", "said", "left", "I", "both", "away", "few", "end", "replied", "say", "said", "came", "anyone", "himself", "must", "saw", "am", "set", 
"put", "themselves", "himself", "instead", "intend", "turn", "open", 
"asked", "gave", "another", "took", "long", "place", "went", "take", 
"find", "my", "can", "do", "into", "will", "first", "I", "itself", 
"became", "part", "should", "having", "even", "known", "form", 
"thing", "things", 'need', "number", "we", "well", "during", "often", "seldom", 
"frequently", "frequent", "seldomly", "being", "use", "useful", "found", "wouldn't", "let's", "making", 
"etc", "more", "what", "would", "anywhere", "are", "not", "may", 
"be", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", 
"still", "some", "once", "since", "I've", "I", "Im", "though", "no", 
"through", "from", "now", "just", "only", "could", "know", "so", 
"Ive", "times", "wasnt", "didnt", "wouldnt", "wont", "cant", "weve", 
"youve", "shes", "hes", "whole", "something", "called", "lived", 
"with", "three", "same", "four", "five", "six", "his", "-", "", 
"I", "me", "you", "your", "yours", "or", "all", "none", "most", 
"much", "far", "again", "stay", "stayed", "said", "did", "came", "is", 
"was", "were", "as", "has", "had", "make", "made", "back", "changed", 
"every", "thing", "each", "everything", "never", "read", "none", "nobody", "does", "doesn't",
"other", "think", "thought", "try", "tried", "held", "hold", "soon", "seen", "you're", "you've", "you'll", "won't", "we've", "we're", "wasn't", "that's", "it's", "hasn't", "weren't", 'want', 'youll', 'yourself',
"quite", "sure", "before", "after", "sooner", "later", "its", "hers", 
"ours", "our", "their", "there", "these", "those", "going", "go", "by", 
"up", "very", "much", "many", "against", "been", "go", "come", "have", 
"also", "instead", "either","else", "any", "such", "were", "where", 
"when", "which", "why", "how", "who", "however", "yet", "he", "him", 
"she", "her", "it", "off", "about", "between", "below", "down", 
"toward", "to", "too", "one", "two", "maybe", "perhaps", "although", 
"because", "instead", "around", "only", "they", "them", "near", "on", 
"following", "next", "before", "after", "a", "an", "had", "at", "for", 
"but", "over", "was", "the", "this", "that", "than", "then", "if", 
"of", "and", "by", "in", "out", "up"];